/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './app/__root'
import { Route as SsoCallbackRouteImport } from './app/sso-callback'
import { Route as SplashRouteImport } from './app/splash'
import { Route as PokedexRouteImport } from './app/pokedex'
import { Route as MenuRouteImport } from './app/menu'
import { Route as IndexRouteImport } from './app/index'
import { Route as DraftRoomCodeRouteImport } from './app/draft.$roomCode'
import { Route as BattleRoomCodeRouteImport } from './app/battle.$roomCode'

const SsoCallbackRoute = SsoCallbackRouteImport.update({
  id: '/sso-callback',
  path: '/sso-callback',
  getParentRoute: () => rootRouteImport,
} as any)
const SplashRoute = SplashRouteImport.update({
  id: '/splash',
  path: '/splash',
  getParentRoute: () => rootRouteImport,
} as any)
const PokedexRoute = PokedexRouteImport.update({
  id: '/pokedex',
  path: '/pokedex',
  getParentRoute: () => rootRouteImport,
} as any)
const MenuRoute = MenuRouteImport.update({
  id: '/menu',
  path: '/menu',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DraftRoomCodeRoute = DraftRoomCodeRouteImport.update({
  id: '/draft/$roomCode',
  path: '/draft/$roomCode',
  getParentRoute: () => rootRouteImport,
} as any)
const BattleRoomCodeRoute = BattleRoomCodeRouteImport.update({
  id: '/battle/$roomCode',
  path: '/battle/$roomCode',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/menu': typeof MenuRoute
  '/pokedex': typeof PokedexRoute
  '/splash': typeof SplashRoute
  '/sso-callback': typeof SsoCallbackRoute
  '/battle/$roomCode': typeof BattleRoomCodeRoute
  '/draft/$roomCode': typeof DraftRoomCodeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/menu': typeof MenuRoute
  '/pokedex': typeof PokedexRoute
  '/splash': typeof SplashRoute
  '/sso-callback': typeof SsoCallbackRoute
  '/battle/$roomCode': typeof BattleRoomCodeRoute
  '/draft/$roomCode': typeof DraftRoomCodeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/menu': typeof MenuRoute
  '/pokedex': typeof PokedexRoute
  '/splash': typeof SplashRoute
  '/sso-callback': typeof SsoCallbackRoute
  '/battle/$roomCode': typeof BattleRoomCodeRoute
  '/draft/$roomCode': typeof DraftRoomCodeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/menu'
    | '/pokedex'
    | '/splash'
    | '/sso-callback'
    | '/battle/$roomCode'
    | '/draft/$roomCode'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/menu'
    | '/pokedex'
    | '/splash'
    | '/sso-callback'
    | '/battle/$roomCode'
    | '/draft/$roomCode'
  id:
    | '__root__'
    | '/'
    | '/menu'
    | '/pokedex'
    | '/splash'
    | '/sso-callback'
    | '/battle/$roomCode'
    | '/draft/$roomCode'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  MenuRoute: typeof MenuRoute
  PokedexRoute: typeof PokedexRoute
  SplashRoute: typeof SplashRoute
  SsoCallbackRoute: typeof SsoCallbackRoute
  BattleRoomCodeRoute: typeof BattleRoomCodeRoute
  DraftRoomCodeRoute: typeof DraftRoomCodeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sso-callback': {
      id: '/sso-callback'
      path: '/sso-callback'
      fullPath: '/sso-callback'
      preLoaderRoute: typeof SsoCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/splash': {
      id: '/splash'
      path: '/splash'
      fullPath: '/splash'
      preLoaderRoute: typeof SplashRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pokedex': {
      id: '/pokedex'
      path: '/pokedex'
      fullPath: '/pokedex'
      preLoaderRoute: typeof PokedexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/menu': {
      id: '/menu'
      path: '/menu'
      fullPath: '/menu'
      preLoaderRoute: typeof MenuRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/draft/$roomCode': {
      id: '/draft/$roomCode'
      path: '/draft/$roomCode'
      fullPath: '/draft/$roomCode'
      preLoaderRoute: typeof DraftRoomCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/battle/$roomCode': {
      id: '/battle/$roomCode'
      path: '/battle/$roomCode'
      fullPath: '/battle/$roomCode'
      preLoaderRoute: typeof BattleRoomCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  MenuRoute: MenuRoute,
  PokedexRoute: PokedexRoute,
  SplashRoute: SplashRoute,
  SsoCallbackRoute: SsoCallbackRoute,
  BattleRoomCodeRoute: BattleRoomCodeRoute,
  DraftRoomCodeRoute: DraftRoomCodeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
